config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :posts

  resources :pages
  get "p/:url" => "pages#show", as: :show_page

  resources :categories
  get "c/:url" => "categories#show", as: :show_category

  get "users" => "accounts#index", as: :users
  delete "account/destroy/:id" => "accounts#destroy_account", as: :destroy_account

  post "message/send" => "public#send_enquiry_to_user", as: :send_enquiry

  get "/dashboard" => "accounts#dashboard", as: :dashboard
  get "/admin/dashboard" => "admin#dashboard", as: :admin_dashboard

  post "locale/set" => "languages#set_locale"

  root to: "public#home"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :account
  has_many_attached :images

  validates_presence_of :account_id, :category_id

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :can_modify_post?, except: [:index, :new, :show, :create]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "#{t('post.singular')} #{t('form.created')}" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "#{t('post.singular')} #{t('form.updated')}" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "#{t('post.singular')} #{t('form.destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def can_modify_post?
      unless current_account.id == @post.account_id || current_account.admin?
        redirect_to root_url, flash: { danger: t("accounts.permission_denied") } and return
      end
    end

    def post_params
      params.fetch(:post, {}).permit(:title, :content, :address, :category_id, images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-12 col-lg-6">
    <%= form_with(model: post, local: true) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title, t("form.label.title") %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :content, t("form.label.content") %>
        <%= form.text_area :content, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :address, t("form.label.location") %>
        <%= form.text_field :address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :category_id, t("form.label.category") %><br />
        <%= form.select :category_id, Category.where.not(parent_id: nil).order(name: :asc).collect {|c| [ c.name, c.id ] }, {}, { class: "form-control" } %>
      </div>

      <div class="input-group mb-3">
        <%= form.label :images, t("form.label.images") %>
        <%= form.file_field :images, multiple: true %>
      </div>

      <% if post.images.attached? %>
        <% post.images.each do |image| %>
          <%= image_tag image, width: "200px" %>
        <% end %>
      <% end %>

      <div class="form-group mt-3">
        <%= form.submit t("form.save"), class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<p class="h4"><%= t("form.edit") %> <%= t("post.singular") %></p>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p class="h4"><%= t("post.plural") %></p>

<table class="table mt-4">
  <thead>
    <tr>
      <th><%= t("form.label.title") %></th>
      <th><%= t("form.label.name") %></th>
      <th><%= t("form.label.date") %></th>
      <th><%= t("form.label.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%= post.account.email %></td>
        <td><%= time_ago_in_words post.created_at %> <%= t 'post.posted' %></td>
        <td>
          <%= link_to "Edit", edit_post_path(post) %> |
          <%= link_to 'Delete', post, method: :delete, data: { confirm: t("form.confirm") } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<p class="h4"><%= t("form.new") %> <%= t("post.singular") %></p>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<span class="posted-at-top float-left"><%= t 'post.posted' %> <%= time_ago_in_words @post.created_at %> <%= t 'post.ago' %></span>

<div class="clearfix">
  <a href="javascript:window.print()" class="btn btn-sm btn-secondary float-right"><%= t 'post.print_button' %></a>
</div>

<% if @post.address.present? %>
  <iframe class="float-right mt-3 ml-3" width="320" height="240" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCSJbOqi0e2d2eXF7kMSdtSQABy_3S1Pz4&q=<%= @post.address.to_param %>" allowfullscreen></iframe>
<% end %>

<h2 class="mt-4 mb-4"><%= @post.title %></h2>

<%= simple_format @post.content %>

<% if @post.images.attached? %>
<div class="clearfix mb-4">
  <% @post.images.each do |image| %>
    <%= link_to image_tag(image, width: "200px", class: "img-thumbnail"), url_for(image), target: "_blank" %>
  <% end %>
</div>
<% end %>

<% unless account_signed_in? && @post.account_id == current_account.id %>

  <%= link_to t("post.send_message"), "#", id: "show_contact_form", class: "btn btn-info" %>

  <div id="contact-form" class="bg-light p-3">
    <div class="row">
      <div class="col-sm-6">
        <%= form_tag send_enquiry_path do %>
          <% user_email = account_signed_in? ? current_account.email : nil %>
          <%= hidden_field_tag :post_id, @post.id %>

          <div class="form-group">
            <%= label_tag :email, t('post.email_label') %>
            <%= text_field_tag :email, user_email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :message, t('post.message_label') %>
            <%= text_area_tag :message, nil, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= submit_tag t('post.send_message_confirm'), class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% end %>