config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :posts

  resources :pages
  get "p/:url" => "pages#show", as: :show_page

  resources :categories
  get "c/:url" => "categories#show", as: :show_category

  get "users" => "accounts#index", as: :users
  delete "account/destroy/:id" => "accounts#destroy_account", as: :destroy_account

  post "message/send" => "public#send_enquiry_to_user", as: :send_enquiry

  get "/dashboard" => "accounts#dashboard", as: :dashboard
  get "/admin/dashboard" => "admin#dashboard", as: :admin_dashboard

  post "locale/set" => "languages#set_locale"

  root to: "public#home"
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :parent, class_name: "Category", optional: true
  has_many :subcategories, class_name: "Category", foreign_key: :parent_id, dependent: :destroy
  has_many :posts

  validates_presence_of :url, :name
  # validates_presence_of :secondary_name

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :can_access?, except: [:show]
  before_action :set_category_by_url, only: [:show]
  before_action :set_category_by_id, only: [:edit, :update, :destroy]

  def index
    @categories = Category.where(parent_id: nil).order(name: :asc)
  end

  def show
    category_ids = @category.subcategories.ids
    category_ids << @category.id

    @posts = Post.where(category_id: category_ids)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "#{t('category.singular')} #{t('form.created')}" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "#{t('category.singular')} #{t('form.updated')}" }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "#{t('category.singular')} #{t('form.destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    def set_category_by_url
      @category = Category.find_by_url(params[:url])
    end

    def set_category_by_id
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.fetch(:category, {}).permit(:name, :secondary_name, :url, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def category_name c
    if I18n.locale != :en
      c.secondary_name.present? ? c.secondary_name : c.name
    else
      c.name
    end
  end

  def category_sort_order
    primary_sort = I18n.locale != :en ? :secondary_name : :name
    secondary_sort = I18n.locale != :en ? :name : :secondary_name
    "#{primary_sort} ASC, #{secondary_sort} ASC"
  end

end

app/views/categories/_category_sidebar.html.erb
<div class="d-none d-lg-block">
  <% if @category.present? %>
    <p><strong><%= category_name(@category) %></strong></p>

    <ul>
      <% @category.subcategories.order(category_sort_order).each do |subcategory| %>
        <li><%= link_to category_name(subcategory), show_category_path(subcategory.url) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>

  <% if category.errors.any? %>
    <div id="error_explanation">
      <strong><%= pluralize(category.errors.count, "error") %></strong>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name, "#{t("form.label.name")} (English)" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name, "#{t("form.label.name")} (Secondary Language)" %>
        <%= form.text_field :secondary_name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :parent_id, t("form.label.parent_category") %>
    <%= form.select :parent_id, Category.where(parent_id: nil).order(name: :asc).collect {|c| [ c.name, c.id ] }, { include_blank: t("form.label.no_parent_category") }, { class: "form-control" } %>
  </div>

  <div class="actions">
    <%= submit_tag t("form.save"), class: "btn btn-success" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h2><%= t("form.edit") %> <%= t("category.singular") %></h2>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<%= link_to "#{t("form.new")} #{t("category.singular")}", new_category_path, class: "btn btn-success float-right" %>

<p class="h4"><%= t("category.plural") %></p>

<table class="table mt-4">
  <thead>
    <tr>
      <th width="70%"><%= t("form.name") %></th>
      <th width="15%"><%= t("form.edit") %></th>
      <th><%= t("form.destroy") %></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr class="bg-light">
        <td class="pt-3 pb-3 pl-3"><strong><%= link_to category_name(category), show_category_path(category.url) %></strong></td>
        <td class="pt-3 pb-3"><%= link_to t("form.edit"), edit_category_path(category.id) %></td>
        <td class="pt-3 pb-3 pr-3"><%= link_to t("form.destroy"), category, method: :delete, data: { confirm: t("form.confirm") } %></td>
      </tr>

      <% category.subcategories.order(category_sort_order).each do |subcategory| %>
        <tr>
          <td class="pl-3"><%= link_to category_name(subcategory), show_category_path(subcategory.url) %></td>
          <td><%= link_to t("form.edit"), edit_category_path(subcategory.id) %></td>
          <td><%= link_to t("form.destroy"), category, method: :delete, data: { confirm: t("form.confirm") } %></td>
        </tr>
      <% end %>

    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<p class="h4"><%= t("form.new") %> <%= t("category.singular") %></p>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<% @posts.each do |post| %>
  <div class="category-post">
    <span class="post-date"><%= time_ago_in_words post.created_at %> ago</span>
    <span class="post-title"><%= link_to post.title, post_path(post) %></span>
  </div>
<% end %>
<% if @posts.empty? %>
  <p>No posts to display.</p>
<% end %>