config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :posts

  resources :pages
  get "p/:url" => "pages#show", as: :show_page

  resources :categories
  get "c/:url" => "categories#show", as: :show_category

  get "users" => "accounts#index", as: :users
  delete "account/destroy/:id" => "accounts#destroy_account", as: :destroy_account

  post "message/send" => "public#send_enquiry_to_user", as: :send_enquiry

  get "/dashboard" => "accounts#dashboard", as: :dashboard
  get "/admin/dashboard" => "admin#dashboard", as: :admin_dashboard

  post "locale/set" => "languages#set_locale"

  root to: "public#home"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  def is_admin?
    self.admin == true
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!, except: [:profile]

  def index
    @users = Account.where(admin: false).order(created_at: :desc)
  end

  def destroy_account
    if params[:id].present? && Account.find_by_id(params[:id]).destroy
      redirect_to users_path, notice: "#{t('users.singular')} #{t('form.destroyed')}"
    else
      redirect_to users_path, flash: { danger: t('form.failed') }
    end
  end

  def dashboard
    @posts = current_account.admin? ? Post.order(created_at: :desc).limit(5) : current_account.posts
    @users = Account.order(created_at: :desc).limit(5) if current_account.admin?
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
  def account_username account
    account.email.present? ? "Welcome back " + account.email.split("@").first.capitalize : "Welcome"
  end
end

app/views/accounts/_dashboard_admin.html.erb
<div class="row mt-4">
  <div class="col-4">
    <div class="p-3 bg-light">
      <p class="h5">Total Users</p>
      <p class="lead"><%= Account.where(admin: false).count %></p>
    </div>
  </div>
  <div class="col-4">
    <div class="p-3 bg-light">
      <p class="h5">Total Posts</p>
      <p class="lead"><%= Post.count %></p>
    </div>
  </div>
  <div class="col-4">
    <div class="p-3 bg-light">
      <p class="h5">Total Pages</p>
      <p class="lead"><%= Page.count %></p>
    </div>
  </div>
</div>

<div class="row mt-4">
  <div class="col">
    <p class="h4">Latest Posts</p>
    <table class="table">
      <thead>
        <tr>
          <th width="70%">Title</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, edit_post_path(post) %></td>
            <td><%= t "post.posted" %> <%= time_ago_in_words post.created_at %> <%= t "post.ago" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row mt-4">
  <div class="col">
    <p class="h4">Latest Users</p>
    <table class="table">
      <thead>
        <tr>
          <th width="70%">Name</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.created_at.strftime("%d %b %Y") %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/accounts/_dashboard_user.html.erb
<div class="mt-4">
<% if @posts.size > 0 %>
  <% @posts.each do |post| %>
    <div class="category-post">
      <span class="post-title"><%= link_to post.title, edit_post_path(post) %></span>
      <span class="post-date">- <%= t "post.posted" %> <%= time_ago_in_words post.created_at %> <%= t "post.ago" %></span>
    </div>
  <% end %>
<% else %>
  <p><%= t("post.no_posts") %></p>
<% end %>
</div>

app/views/accounts/_sidebar_admin.html.erb
<div class="nav-admin mt-4 mb-5">
  <p><strong>Admin Nav</strong></p>
  <ul>
    <li><%= link_to "Dashboard", dashboard_path %></li>
    <li><%= link_to "Categories", categories_path %></li>
    <li><%= link_to "Pages", pages_path %></li>
    <li><%= link_to "Posts", posts_path %></li>
    <li><%= link_to "Users", users_path %></li>
  </ul>
</div>

app/views/accounts/dashboard.html.erb
<p class="h4"><%= t "dashboard.title" %></p>

<% if current_account.admin? %>
  <%= render "dashboard_admin" %>
<% else %>
  <%= render "dashboard_user" %>
<% end %>

app/views/accounts/index.html.erb
<p class="h4"><%= t("users.plural") %></p>

<table class="table mt-4">
  <thead>
    <tr>
      <th width="50%"><%= t("form.label.email") %></th>
      <th width="25%"><%= t("form.label.date") %></th>
      <th><%= t("form.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%d %b %Y") %></td>
        <td>
          <%= link_to t("form.destroy"), destroy_account_path(user.id), method: :delete, data: { confirm: t("form.confirm") } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>